### PR TITLE
Added 4 companies

### PR DESCRIPTION
**Pull request by Alpha-Knight-Zero**
Added 4 companies :- Crowdstrike, Xiaomi, Bain & Co, Grant Thornton
Update company number to 221 up from 217.

### CODE REVIEW

**Comment by Kaustubh-Natuskar** [comment]
Please Numbering according to guidelines

**Comment by Kaustubh-Natuskar** [comment]
Creating merge conflicts. See what's happening

**Comment by Alpha-Knight-Zero** [comment]
> Creating merge conflicts. See what's happening

Alphabetical order was wrong in one case. Corrected it.

**Comment by iyoushe1703** [comment]
Please resolve merge conflicts on your end.

**Comment by Alpha-Knight-Zero** [comment]
> Please resolve merge conflicts on your end.

<<<<<<< main
 |      222            |
=======
 |      233            |
>>>>>>> main

what is this suppose to mean , I had added 5 to 217(which was already on the repo)
but its is showing 233

**Comment by Alpha-Knight-Zero** [comment]
> > Please resolve merge conflicts on your end.
> 
> # <<<<<<< main
> | 222 |
> | 233 |
> 
> > > > > > > > main
> 
> what is this suppose to mean , I had added 5 to 217(which was already on the repo) but its is showing 233

Also this
<<<<<<< main
1.   [Xiaomi](https://xiaomi.app.param.ai/jobs/)   
    
=======
>>>>>>> main

**Comment by iyoushe1703** [comment]
It means you have to first fetch the recent commits and then make your changes on top of that

**Comment by Alpha-Knight-Zero** [comment]
> It means you have to first fetch the recent commits and then make your changes on top of that

I think its done now.

**Pull request merged**
