### PR TITLE
Added 3i Infotech Company

### PR DESCRIPTION
**Pull request by Manish-kasera**

### CODE REVIEW

**Comment by Kaustubh-Natuskar** [comment]
You forgot to change count.

**Comment by Manish-kasera** [comment]
Just a Second.

**Comment by Manish-kasera** [comment]
Count increase by 1

**Comment by Kaustubh-Natuskar** [comment]
Thank you.

**Comment by Kaustubh-Natuskar** [comment]
Next time don't forget to add description.

**Comment by Manish-kasera** [comment]
Thank you for telling this.. Hope I will never forget.

**Pull request merged**
