### PR TITLE
Suggest Name for Repository

### PR DESCRIPTION
**Pull request by nishant-giri**
## Related Issue
Issue #130.

## Suggestions
* Applymen
* ApplyFocus
* CoApply

### CODE REVIEW

**Comment by Kaustubh-Natuskar** [comment]
Nah...

**Comment by nishant-giri** [comment]
@Kaustubh-Natuskar, shall I add few Issue templates too? I was just going through your repository.

**Comment by Kaustubh-Natuskar** [comment]
Who closed this issue ?

**Comment by Kaustubh-Natuskar** [comment]
We are not closing this issue untill we get a proper name.

**Pull request closed without merging**
